_types:
  pattern:
    peer:
      '@freesewing/core': '^{{version}}'
      '@freesewing/plugin-bundle': '^{{version}}'
    dev:
      'react': '^16.13.1'
      'react-dom': '^16.13.1'
      '@babel/plugin-proposal-class-properties': '^7.10.4'
      'babel-eslint': '^10.1.0'
      'eslint': '^7.6.0'
      'babel-jest': '^26.2.2'
      'jest': '26.2.2'
      '@freesewing/components': '^{{version}}'
      '@freesewing/css-theme': '^{{version}}'
      '@freesewing/i18n': '^{{version}}'
      '@freesewing/mui-theme': '^{{version}}'
      '@freesewing/plugin-bust': '^{{version}}'
      '@freesewing/plugin-buttons': '^{{version}}'
      '@freesewing/plugin-flip': '^{{version}}'
      '@freesewing/utils': '^{{version}}'
      '@svgr/rollup': '^2.4.1'
      'cross-env': '^7.0.2'
      'react-scripts': '^3.4.1'
      'webpack': '^4.44.1'
      'rollup': '^2.23.0'
      '@rollup/plugin-babel': '^5.1.0'
      'rollup-plugin-terser': '^6.1.0'
      '@rollup/plugin-commonjs': '^14.0.0'
      '@rollup/plugin-json': '^4.1.0'
      '@rollup/plugin-node-resolve': '^8.4.0'
      'rollup-plugin-peer-deps-external': '^2.2.3'
      '@material-ui/core': '^4.11.0'
      '@material-ui/icons': '4.9.1'
      '@material-ui/lab': '^v4.0.0-alpha.56'
      'react-intl': '^5.4.5'
      'prop-types': '^15.7.2'
      'mocha': '^8.1.0'
      'chai': '^4.2.0'
      'chai-string': '^1.5.0'
      '@babel/register': '^7.10.5'
  plugin:
    peer:
      '@freesewing/core': '^{{version}}'
aaron:
  peer:
    '@freesewing/brian': '^{{version}}'
bent:
  peer:
    '@freesewing/brian': '^{{version}}'
breanna:
  peer:
    '@freesewing/brian': '^{{version}}'
carlita:
  peer:
    '@freesewing/brian': '^{{version}}'
    '@freesewing/bent': '^{{version}}'
    '@freesewing/carlton': '^{{version}}'
    '@freesewing/plugin-bust': '^{{version}}'
    '@freesewing/plugin-buttons': '^{{version}}'
carlton:
  peer:
    '@freesewing/brian': '^{{version}}'
    '@freesewing/bent': '^{{version}}'
    '@freesewing/plugin-buttons': '^{{version}}'
css-theme:
  _:
    'open-color': '^1.7.0'
components:
  peer:
    'react': '^16.13.1'
    '@freesewing/pattern-info': '^{{version}}'
    '@freesewing/mui-theme': '^{{version}}'
    '@freesewing/css-theme': '^{{version}}'
    '@freesewing/plugin-theme': '^{{version}}'
    '@freesewing/core': '^{{version}}'
    '@freesewing/models': '^{{version}}'
    '@freesewing/examples': '^{{version}}'
    '@freesewing/rendertest': '^{{version}}'
    '@freesewing/tutorial': '^{{version}}'
    'typeface-roboto-condensed': 'latest'
    '@freesewing/i18n': '^{{version}}'
    '@freesewing/utils': '^{{version}}'
    'react-intl': '^5.4.5'
    '@material-ui/core': '^4.11.0'
    '@material-ui/icons': '4.9.1'
    '@material-ui/lab': '^v4.0.0-alpha.56'
    'prismjs': '^1.20.0'
    'react-markdown': '^4.3.1'
    'file-saver': '^2.0.2'
    'yaml': '^1.10.0'
core:
  _:
    'bezier-js': '^3.0.1'
    'bin-pack': '^1.0.2'
    'hooks': '^0.3.2'
create-freesewing-pattern:
  _:
    'chalk': '^4.1.0'
    'commander': '^6.0.0'
    'conf': '^7.1.1'
    'cp-file': '^9.0.0'
    'execa': '^4.0.3'
    'git-config-path': '^2.0.0'
    'github-username': '^5.0.1'
    'globby': '^11.0.1'
    'handlebars': '^4.7.6'
    'inquirer': '^7.3.3'
    'make-dir': '^3.1.0'
    'ora': '^4.0.5'
    'p-each-series': '^2.1.0'
    'parse-git-config': '^3.0.0'
    'validate-npm-package-name': '^3.0.0'
    'which': '^2.0.2'
    '@freesewing/i18n': '^{{version}}'
    '@freesewing/pattern-info': '^{{version}}'
diana:
  peer:
    '@freesewing/brian': '^{{version}}'
gatsby-remark-jargon:
  _:
    'remark-jargon': '^{{version}}'
holmes:
  _:
    '@freesewing/plugin-gore': '^{{version}}'
  peer:
    '@freesewing/plugin-bust': '^{{version}}'
huey:
  peer:
    '@freesewing/brian': '^{{version}}'
hugo:
  peer:
    '@freesewing/brian': '^{{version}}'
i18n:
  peer:
    '@freesewing/pattern-info': '^{{version}}'
jaeger:
  peer:
    '@freesewing/brian': '^{{version}}'
    '@freesewing/bent': '^{{version}}'
    '@freesewing/plugin-buttons': '^{{version}}'
models:
  peer:
    '@freesewing/utils': '^{{version}}'
mui-theme:
  peer:
    '@material-ui/core': '^4.11.0'
    'react': '^16.13.1'
    'react-dom': '^16.13.1'
legend:
  peer:
    '@freesewing/plugin-buttons': '^{{version}}'
paco:
  peer:
    '@freesewing/titan': '^{{version}}'
plugin-bundle:
  _:
    '@freesewing/plugin-cutonfold': '^{{version}}'
    '@freesewing/plugin-dimension': '^{{version}}'
    '@freesewing/plugin-grainline': '^{{version}}'
    '@freesewing/plugin-logo': '^{{version}}'
    '@freesewing/plugin-title': '^{{version}}'
    '@freesewing/plugin-scalebox': '^{{version}}'
    '@freesewing/plugin-round': '^{{version}}'
    '@freesewing/plugin-sprinkle': '^{{version}}'
remark-jargon:
  _:
    'unist-util-visit': '^2.0.3'
  peer:
    'remark': '^12.0.1'
    'remark-html': '^12.0.0'
simon:
  peer:
    '@freesewing/brian': '^{{version}}'
    '@freesewing/plugin-buttons': '^{{version}}'
    '@freesewing/plugin-flip': '^{{version}}'
simone:
  peer:
    '@freesewing/brian': '^{{version}}'
    '@freesewing/simon': '^{{version}}'
    '@freesewing/plugin-buttons': '^{{version}}'
    '@freesewing/plugin-flip': '^{{version}}'
    '@freesewing/plugin-bust': '^{{version}}'
sven:
  peer:
    '@freesewing/brian': '^{{version}}'
teagan:
  peer:
    '@freesewing/brian': '^{{version}}'
    '@freesewing/plugin-bust': '^{{version}}'
utils:
  peer:
    'tlds': '^1.207.0'
    'axios': '^0.19.2'
wahid:
  peer:
    '@freesewing/brian': '^{{version}}'
    '@freesewing/plugin-buttons': '^{{version}}'
    '@freesewing/plugin-round': '^{{version}}'
